export {default as NavBar} from './NavBar/Navbar'
export {default as ContactForm} from './ContactUs/ContactForm'
export {default as AboutUs} from './AboutUs/AboutUs'
export {default as Shop} from './Shop/Shop'
export {default as Main} from './LandPage/Main'
export {default as Footer} from './Footer/Footer'